apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsome-app-flux
  labels:
    app: app
  annotations:
    fluxcd.io/automated: "true"  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awsome-app-flux
  template:
    metadata:
      labels:
        app: awsome-app-flux
    spec:
      containers:
      - name: awsome-app-flux
        image: 957288871734.dkr.ecr.ap-southeast-1.amazonaws.com/images
        ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
        
